# Not recommended to actually run `pre-commit install` because the codebase is not very stable
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # must match test-requirements.txt
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0  # must match test-requirements.txt
    hooks:
      - id: ruff  # Linter
        args: [ --fix ]
      - id: ruff-format  # Auto-formatter
