# This file is manually created and maintained, please refer to requirements.txt as source of truth
name: redstone-squid
channels:
  - conda-forge
dependencies:
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - anyio=4.3.0
  - asgiref=3.8.1
  - attrs=23.2.0
  - blinker=1.8.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cachetools=5.3.3
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - configparser=7.0.0
  - cryptography=42.0.7
  - deprecation=2.1.0
  - django=5.0.6
  - dnspython=2.4.2
  - email-validator=2.1.1
  - email_validator=2.1.1
  - exceptiongroup=1.2.0
  - fastapi=0.111.0
  - fastapi-cli=0.0.3
  - frozenlist=1.4.1
  - gitdb=4.0.11
  - gitpython=3.1.43
  - google-auth=2.29.0
  - google-auth-oauthlib=1.2.0
  - gotrue=2.4.2
  - gspread=5.12.4
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httplib2=0.22.0
  - httpx=0.25.2
  - hyperframe=6.0.1
  - idna=3.7
  - krb5=1.21.2
  - libexpat=2.6.2
  - libffi=3.4.2
  - libpq=16.3
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - multidict=6.0.5
  - oauth2client=4.1.3
  - oauthlib=3.2.2
  - openssl=3.3.0
  - orjson=3.10.3
  - packaging=24.0
  - pip=24.0
  - postgrest=0.16.4
  - psycopg2=2.9.9
  - psycopg2-binary=2.9.9
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pydantic=2.7.1
  - pydantic-core=2.18.2
  - pygments=2.18.0
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-multipart=0.0.9
  - python_abi=3.12
  - pyu2f=0.1.5
  - realtime=1.0.4
  - requests=2.31.0
  - requests-oauthlib=2.0.0
  - rich=13.7.1
  - rsa=4.9
  - setuptools=69.5.1
  - shellingham=1.5.4
  - six=1.16.0
  - smmap=5.0.0
  - sniffio=1.3.1
  - sqlparse=0.5.0
  - starlette=0.37.2
  - storage3=0.7.4
  - strenum=0.4.15
  - tk=8.6.13
  - typer=0.12.3
  - typer-slim=0.12.3
  - typer-slim-standard=0.12.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - ujson=5.9.0
  - urllib3=2.2.1
  - uvicorn=0.29.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.2.6
  - yarl=1.9.4
  - pip:
      - argcomplete==3.2.3
      - build==1.2.1
      - commitizen==3.21.3
      - decli==0.6.1
      - discord==2.3.2
      - discord-py==2.3.2
      - importlib-metadata==7.1.0
      - jinja2==3.1.3
      - pip-tools==7.4.1
      - prompt-toolkit==3.0.36
      - pyproject-hooks==1.1.0
      - pyyaml==6.0.1
      - questionary==2.0.1
      - supabase-py-async==2.5.6
      - supafunc==0.4.0
      - termcolor==2.4.0
      - tomlkit==0.12.4
      - wcwidth==0.2.13
      - websockets==11.0.3
      - zipp==3.18.1
