[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.11"
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.in"] }
optional-dependencies.test = { file = ["requirements-test.txt"] }

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.format]
docstring-code-format = true

[tool.pyright]
pythonVersion = "3.12"
pythonPlatform = "Linux"
reportUnnecessaryTypeIgnoreComment = "information"