CREATE TABLE public.type_aliases (
  type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  alias TEXT NOT NULL UNIQUE,
  CONSTRAINT type_aliases_pkey PRIMARY KEY (alias),
  CONSTRAINT type_aliases_type_id_fkey
    FOREIGN KEY (type_id) REFERENCES public.types (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- Index on type_id
CREATE INDEX type_aliases_type_id_idx
  ON public.type_aliases (type_id);

-- Validate the foreign key constraint
ALTER TABLE public.type_aliases
  VALIDATE CONSTRAINT type_aliases_type_id_fkey;

-- Enable row-level security
ALTER TABLE public.type_aliases ENABLE ROW LEVEL SECURITY;

grant delete on table "public"."type_aliases" to "anon";
grant insert on table "public"."type_aliases" to "anon";
grant references on table "public"."type_aliases" to "anon";
grant select on table "public"."type_aliases" to "anon";
grant trigger on table "public"."type_aliases" to "anon";
grant truncate on table "public"."type_aliases" to "anon";
grant update on table "public"."type_aliases" to "anon";
grant delete on table "public"."type_aliases" to "authenticated";
grant insert on table "public"."type_aliases" to "authenticated";
grant references on table "public"."type_aliases" to "authenticated";
grant select on table "public"."type_aliases" to "authenticated";
grant trigger on table "public"."type_aliases" to "authenticated";
grant truncate on table "public"."type_aliases" to "authenticated";
grant update on table "public"."type_aliases" to "authenticated";
grant delete on table "public"."type_aliases" to "service_role";
grant insert on table "public"."type_aliases" to "service_role";
grant references on table "public"."type_aliases" to "service_role";
grant select on table "public"."type_aliases" to "service_role";
grant trigger on table "public"."type_aliases" to "service_role";
grant truncate on table "public"."type_aliases" to "service_role";
grant update on table "public"."type_aliases" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."type_aliases"
as permissive
for insert
to authenticated
with check (true);

create policy "Enable read access for all users"
on "public"."type_aliases"
as permissive
for select
to public
using (true);
