name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]
    branches: [master]
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    if: >-
      github.event_name == 'workflow_dispatch' || 
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4\
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd Redstone-Squid
            bash ./scripts/deploy.sh -d
