name: Continuous Deployment

permissions: {}

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]
    branches: [master]
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:
    if: >-
      github.event_name == 'workflow_dispatch' || 
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # https://github.com/appleboy/ssh-action/issues/31#issuecomment-1006565847
          # Note that because .bashrc does nothing by default for non-interactive shells,
          # we actually need to edit the .bashrc file to get the environment variables to load.
          # In particular, I edited the .bashrc file to add uv to the PATH regardless of whether the shell
          # is interactive or not by adding the following line at the START of the file:
          #
          # export PATH="$HOME/.local/bin:$PATH"
          #
          # This is quite a hacky solution, but it works for now.
          # Also, you need to set up the repo on the server first.
          script: |
            source ~/.bashrc
            cd Redstone-Squid
            bash ./scripts/deploy.sh -d
