name: Continuous Integration

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        # Install a specific version of uv.
        version: "0.6.14"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Check all files have corresponding gitattributes
      run: |  # https://github.com/gitattributes/gitattributes
        missing_attributes=$(git ls-files | git check-attr -a --stdin | grep 'text: auto' || printf '\n')
        if [ -n "$missing_attributes" ]; then
          printf '%s\n%s\n' '.gitattributes rule missing for the following files:' "$missing_attributes"
        else
          printf '%s\n' 'All files have a corresponding rule in .gitattributes'
        fi

    - name: See if there are linting or formatting issues
      run: uv run ruff check --extend-select I

    - name: See if there are linting or formatting issues
      run: uv run ruff format --target-version py312 --check

    - name: See if there are type checking issues
      run: uv run basedpyright --level=warning

    - name: Run tests
      run: uv run pytest tests --cov=squid --cov-report=term-missing --cov-report=html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage (${{ github.event_name }}) (${{ matrix.python-version }})
        path: htmlcov/

    - name: Minimize uv cache
      run: uv cache prune --ci