name: Deployment
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          pkill -f "app.py" || true
          nohup ~/Redstone-Squid/venv/bin/python3 app.py &