name: Deployment
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run python
        run: |
          pkill -f "app.py" || true
          ~/Redstone-Squid/venv/bin/python3 -m pip-sync requirements.txt
          # The following is needed to run the app in the background
          # See: https://github.com/actions/runner/issues/598#issuecomment-1703807030
          RUNNER_TRACKING_ID="" && (nohup ~/Redstone-Squid/venv/bin/python3 app.py &)